### ISSUE TITLE
Clicking add transaction button gives back error code 400 (bad request)

### ISSUE THREAD

**Issue by joshcwinton** [rvente/PerFi#46]
<img width="1392" alt="Screen Shot 2019-06-20 at 11 58 55 PM" src="https://user-images.githubusercontent.com/29495809/59896651-5ec86380-93b7-11e9-8865-2f5c34936398.png">

**Comment by rvente** [comment]
known issue: default category doesn't get set so, post fails. Fixed upstream a few minutes ago on master.
